### ISSUE TITLE
Is the Chian edition of the Iliad a thing?

### ISSUE THREAD

**Issue by brclar15** [hmteditors/venA-19#2]
urn:cts:greekLit:tlg5026.msA.hmt:19.2015office9_12

Is it Chios the place? Or is it parallel to the other city edition of the _Iliad_?

**Comment by brclar15** [comment]
like that Μασσαλιωτικῇ Iliad

**Comment by StephanieML** [comment]
city edition of the Iliad, yes. We've seen it show up a couple times in Iliad 9. Kinda cool. I think we'll want to treat it as a lexmapping item when it fails.

**Comment by brclar15** [comment]
taken care of
